### PR TITLE
Use a loader while generating addresses

### PR DESCRIPTION
**Pull request by bokub**
I added nice logs and a spinning loader. Useful to see that the program is running and not stuck.

It doesn't affect the file log at all ( -l option )

animated screenshot

loader

### CODE REVIEW

**Comment by bokub** [comment]
Hi,
I'm not sure who is supposed to review this PR, @kvhnuke is the author of 100% of the code, but has not committed for months.

Is it @tayvano ?

**Comment by kvhnuke** [comment]
Thanks @bokub that's a really cool addition :)

**Comment by bokub** [comment]
You're welcome!

Don't forget to NPM publish :+1:

**Comment by bokub** [comment]
Hi @kvhnuke , I see that the last version of `vanity-eth` is still 1.0.4  on NPM.

Is there a particular reason you don't want to publish, or did you just forget to do it?

**Comment by kvhnuke** [comment]
Ooops yes completely forgot I was working on another project. My bad! Will do it now

**Comment by kvhnuke** [comment]
Published! Thanks again!

**Pull request merged**
